version: '3.7'

services:
  backend:
    build: .
    command: sh /usr/src/pre_start.sh
    env_file:
      - ".env"
    volumes:
      - .:/usr/src/
    ports:
      - 8002:8000
    depends_on:
      - db
  db:
    image: postgres:latest
    env_file:
      - ".env"

    volumes:
      - ./postgres_data:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_PORT: ${DATABASE_PORT}
      #POSTGRES_HOST: ${DATABASE_HOST}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5431:5432
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db
volumes:
  postgres_data:
